/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OralRouteImport } from './routes/oral'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as ThemeThemeIdRouteImport } from './routes/theme.$themeId'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as VocabIndexRouteImport } from './routes/vocab.index'
import { Route as VocabQuizRouteImport } from './routes/vocab.quiz'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OralRoute = OralRouteImport.update({
  id: '/oral',
  path: '/oral',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeThemeIdRoute = ThemeThemeIdRouteImport.update({
  id: '/theme/$themeId',
  path: '/theme/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabIndexRoute = VocabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VocabRoute,
} as any)
const VocabQuizRoute = VocabQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => VocabRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/oral': typeof OralRoute
  '/review': typeof ReviewRoute
  '/themes': typeof ThemesRoute
  '/vocab': typeof VocabRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/vocab/quiz': typeof VocabQuizRoute
  '/vocab/': typeof VocabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/oral': typeof OralRoute
  '/review': typeof ReviewRoute
  '/themes': typeof ThemesRoute
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/vocab/quiz': typeof VocabQuizRoute
  '/vocab': typeof VocabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/oral': typeof OralRoute
  '/review': typeof ReviewRoute
  '/themes': typeof ThemesRoute
  '/vocab': typeof VocabRouteWithChildren
  '/theme/$themeId': typeof ThemeThemeIdRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/vocab/quiz': typeof VocabQuizRoute
  '/vocab/': typeof VocabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/favorites'
    | '/login'
    | '/oral'
    | '/review'
    | '/themes'
    | '/vocab'
    | '/theme/$themeId'
    | '/topic/$slug'
    | '/vocab/quiz'
    | '/vocab/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/favorites'
    | '/login'
    | '/oral'
    | '/review'
    | '/themes'
    | '/theme/$themeId'
    | '/topic/$slug'
    | '/vocab/quiz'
    | '/vocab'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/favorites'
    | '/login'
    | '/oral'
    | '/review'
    | '/themes'
    | '/vocab'
    | '/theme/$themeId'
    | '/topic/$slug'
    | '/vocab/quiz'
    | '/vocab/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  OralRoute: typeof OralRoute
  ReviewRoute: typeof ReviewRoute
  ThemesRoute: typeof ThemesRoute
  VocabRoute: typeof VocabRouteWithChildren
  ThemeThemeIdRoute: typeof ThemeThemeIdRoute
  TopicSlugRoute: typeof TopicSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral': {
      id: '/oral'
      path: '/oral'
      fullPath: '/oral'
      preLoaderRoute: typeof OralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/$themeId': {
      id: '/theme/$themeId'
      path: '/theme/$themeId'
      fullPath: '/theme/$themeId'
      preLoaderRoute: typeof ThemeThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/': {
      id: '/vocab/'
      path: '/'
      fullPath: '/vocab/'
      preLoaderRoute: typeof VocabIndexRouteImport
      parentRoute: typeof VocabRoute
    }
    '/vocab/quiz': {
      id: '/vocab/quiz'
      path: '/quiz'
      fullPath: '/vocab/quiz'
      preLoaderRoute: typeof VocabQuizRouteImport
      parentRoute: typeof VocabRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VocabRouteChildren {
  VocabQuizRoute: typeof VocabQuizRoute
  VocabIndexRoute: typeof VocabIndexRoute
}

const VocabRouteChildren: VocabRouteChildren = {
  VocabQuizRoute: VocabQuizRoute,
  VocabIndexRoute: VocabIndexRoute,
}

const VocabRouteWithChildren = VocabRoute._addFileChildren(VocabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  OralRoute: OralRoute,
  ReviewRoute: ReviewRoute,
  ThemesRoute: ThemesRoute,
  VocabRoute: VocabRouteWithChildren,
  ThemeThemeIdRoute: ThemeThemeIdRoute,
  TopicSlugRoute: TopicSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
